import { FileText } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsPage() {
  return (
    <div className="bg-[var(--color-bg)] animate-fade-in">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Header */}
        <div className="mb-10">
          <div className="inline-flex items-center gap-2 bg-blue-100 dark:bg-blue-900/30 text-[var(--color-primary)] text-xs font-semibold px-4 py-1.5 rounded-full mb-4">
            <FileText size={13} /> Legal
          </div>
          <h1 className="text-3xl font-extrabold text-[var(--color-text)] mb-2">Terms &amp; Conditions</h1>
          <p className="text-[var(--color-text-muted)] text-sm">Last updated: April 2026</p>
        </div>

        <div className="space-y-8 text-[var(--color-text)]">

          <section>
            <h2 className="text-lg font-bold mb-2">1. Acceptance of Terms</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              By accessing or using ExamPrep AI ("the platform"), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">2. Account Registration</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You may not share your account with others or impersonate any person or entity.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">3. Use of the Platform</h2>
            <ul className="text-[var(--color-text-muted)] text-sm space-y-1.5 list-disc list-inside leading-relaxed">
              <li>Use the platform only for lawful purposes.</li>
              <li>Do not attempt to reverse-engineer, scrape, or exploit the platform.</li>
              <li>Do not use automated tools to generate exams in bulk beyond your plan limit.</li>
              <li>Do not share, redistribute, or resell exam content generated by the platform.</li>
              <li>Do not attempt to bypass AI proctoring or cheat during proctored exams.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">4. Subscription Plans &amp; Payments</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              ExamPrep AI offers Free, Pro, and Enterprise plans. Paid plans are billed monthly via Razorpay. Prices are shown in Indian Rupees (INR) and are inclusive of applicable taxes. Subscriptions auto-renew unless cancelled. Refunds are handled at our discretion — contact us within 7 days of a charge if you believe there is an error.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">5. Certificates</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              Certificates issued by ExamPrep AI are for personal achievement tracking only. They are not accredited qualifications unless explicitly stated. We do not guarantee that third parties (employers, universities) will accept them as formal credentials.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">6. AI-Generated Content</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              Exam questions are generated by AI and may occasionally contain errors. We do not warrant the accuracy, completeness, or suitability of AI-generated content for any specific purpose. Users are encouraged to verify answers using additional study materials.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">7. Proctoring &amp; Privacy</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              Proctored exams require webcam access. By taking a proctored exam, you consent to the capture and storage of webcam snapshots during the session. These are used solely for exam integrity purposes and may be reviewed by the exam instructor.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">8. Termination</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent activity, or misuse the platform. You may delete your account at any time via the profile settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">9. Limitation of Liability</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              ExamPrep AI is provided "as is" without any warranties. To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">10. Governing Law</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold mb-2">11. Contact</h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed text-sm">
              For any questions regarding these Terms, please reach us via the <Link to="/contact" className="text-[var(--color-primary)] hover:underline">Contact page</Link>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
